apiVersion: apps/v1
kind: Deployment
metadata:
  name: weather-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: weather
  template:
    metadata:
      labels:
        app: weather
    spec:
      containers:
        - name: weather
          image: ghcr.io/schultyy/weatherapi:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 4000
          env:
            - name: API_TOKEN
              value: Token12345
---
apiVersion: v1
kind: Service
metadata:
  name: weather-service
spec:
  selector:
    app: weather
  ports:
    - protocol: TCP
      port: 4000
      targetPort: 4000
  type: ClusterIP

