apiVersion: apps/v1
kind: Deployment
metadata:
  name: secrets-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: secrets
  template:
    metadata:
      labels:
        app: secrets
    spec:
      containers:
        - name: secrets
          image: ghcr.io/schultyy/secrets:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          env:
            - name: WEATHER_API_TOKEN
              value: Token12345
            - name: WEATHER_API_ENDPOINT
              value: weather-service.default.svc.cluster.local:4000
---
apiVersion: v1
kind: Service
metadata:
  name: secrets-service
spec:
  selector:
    app: secrets
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 3000
  type: ClusterIP

